### PR TITLE
Adapt to latest iteration of llvm+wasm2c.

### PR DESCRIPTION
**Pull request by matthias-blume**
This can use varargs functions directly, so we can use the unmodified native_app_glue (and printf).

### CODE REVIEW

**Review by dimitry- — APPROVED** [review]
I think we need liblog symbols in wasn_ndk for this to work, right?

**Comment by matthias-blume** [comment]
> I think we need liblog symbols in wasn_ndk for this to work, right?

I tend to agree, but for some reason it compiled and worked when I tried it.
I'm in a meeting now.  I can try to investigate later how that happened.

**Comment by matthias-blume** [comment]
I'm a bit baffled by the fact that we don't seem to need liblog symbols.  In fact, I currently don't understand the mechanics.  However, after I run cmake and then look at the result using wasm-objdump, I don't see any mention of any of the liblog symbols.

**Comment by dimitry-** [comment]
I think this is because of log.h header introduced in wasm_ndk, I will remove it and see what happens.

**Comment by matthias-blume** [comment]
> I think this is because of log.h header introduced in wasm_ndk, I will remove it and see what happens.

Ah - that is very plausible!  There had to be a rational explanation, and I was completely oblivious of this header file.

Do you still want me to merge this PR for the time being?  It does compile and work fine, even if only by some amount of accident...

**Comment by dimitry-** [comment]
yes - let's merge this one.

**Comment by matthias-blume** [comment]
> yes - let's merge this one.

Done.

**Pull request merged**
